# It's a bit tricky to reliably find the runtime DLLs of a target, 
# because CMake's target properties don't directly distinguish between
# link dependencies that are runtime libraries and those that are not. 
# This module implements a heuristic approach to find the runtime DLLs
# of a target by recursively inspecting its link dependencies and
# checking their properties.

# It's used instead of CMake's built-in generator expression 
# $<TARGET_RUNTIME_DLLS> which requires CMake 3.27.

set(NOVAPHY_FIND_DLLS_DEBUG OFF CACHE BOOL
    "Enable debug logs for find_target_dlls"
)

function(_novaphy_find_dlls_log message_text)
    if (NOVAPHY_FIND_DLLS_DEBUG)
        message(STATUS "[find-target-dlls] ${message_text}")
    endif()
endfunction()

function(_novaphy_resolve_alias_target in_target out_target)
    set(_resolved "${in_target}")
    get_target_property(_aliased "${in_target}" ALIASED_TARGET)
    if (_aliased)
        set(_resolved "${_aliased}")
    endif()
    set(${out_target} "${_resolved}" PARENT_SCOPE)
endfunction()

function(_novaphy_peel_wrapper_genex item out_inner out_matched)
    set(_inner "${item}")
    set(_matched FALSE)

    if ("${item}" MATCHES "^\\$<LINK_ONLY:(.+)>$")
        set(_inner "${CMAKE_MATCH_1}")
        set(_matched TRUE)
    elseif ("${item}" MATCHES "^\\$<TARGET_NAME_IF_EXISTS:(.+)>$")
        set(_inner "${CMAKE_MATCH_1}")
        set(_matched TRUE)
    elseif ("${item}" MATCHES "^\\$<BUILD_INTERFACE:(.+)>$")
        set(_inner "${CMAKE_MATCH_1}")
        set(_matched TRUE)
    elseif ("${item}" MATCHES "^\\$<INSTALL_INTERFACE:(.+)>$")
        set(_inner "${CMAKE_MATCH_1}")
        set(_matched TRUE)
    endif()

    set(${out_inner} "${_inner}" PARENT_SCOPE)
    set(${out_matched} ${_matched} PARENT_SCOPE)
endfunction()

function(_novaphy_extract_targets_from_link_item item out_targets)
    set(_targets "")

    if ("${item}" STREQUAL "" OR
        "${item}" STREQUAL "debug" OR
        "${item}" STREQUAL "optimized" OR
        "${item}" STREQUAL "general")
        set(${out_targets} "" PARENT_SCOPE)
        return()
    endif()

    _novaphy_peel_wrapper_genex("${item}" _inner _matched)
    if (_matched)
        _novaphy_find_dlls_log("Peel genex item='${item}' -> inner='${_inner}'")
        set(_parts "${_inner}")
        foreach(_part IN LISTS _parts)
            _novaphy_extract_targets_from_link_item("${_part}" _part_targets)
            if (_part_targets)
                list(APPEND _targets ${_part_targets})
            endif()
        endforeach()
    else()
        set(_parts "${item}")
        foreach(_part IN LISTS _parts)
            if (TARGET "${_part}")
                list(APPEND _targets "${_part}")
            else()
                _novaphy_find_dlls_log("Skip non-target link item part='${_part}' from item='${item}'")
            endif()
        endforeach()
    endif()

    if (_targets)
        list(REMOVE_DUPLICATES _targets)
    endif()
    set(${out_targets} "${_targets}" PARENT_SCOPE)
endfunction()

function(_novaphy_link_item_mode_matches mode out_matches)
    set(_matches TRUE)

    if (mode STREQUAL "debug")
        if (NOT CMAKE_CONFIGURATION_TYPES)
            if (NOT CMAKE_BUILD_TYPE STREQUAL "Debug")
                set(_matches FALSE)
            endif()
        endif()
    elseif (mode STREQUAL "optimized")
        if (NOT CMAKE_CONFIGURATION_TYPES)
            if (CMAKE_BUILD_TYPE STREQUAL "Debug")
                set(_matches FALSE)
            endif()
        endif()
    endif()

    set(${out_matches} ${_matches} PARENT_SCOPE)
endfunction()

function(_novaphy_get_target_link_targets target out_targets)
    set(_targets "")

    foreach(_prop IN ITEMS LINK_LIBRARIES INTERFACE_LINK_LIBRARIES)
        get_target_property(_items "${target}" ${_prop})
        if (NOT _items OR _items STREQUAL "_items-NOTFOUND")
            _novaphy_find_dlls_log("Target '${target}' has no ${_prop}")
            continue()
        endif()
        _novaphy_find_dlls_log("Target '${target}' ${_prop}='${_items}'")

        set(_next_item_mode "general")
        foreach(_item IN LISTS _items)
            if ("${_item}" STREQUAL "debug" OR
                "${_item}" STREQUAL "optimized" OR
                "${_item}" STREQUAL "general")
                set(_next_item_mode "${_item}")
                continue()
            endif()

            _novaphy_link_item_mode_matches("${_next_item_mode}" _mode_matches)
            set(_next_item_mode "general")
            if (NOT _mode_matches)
                _novaphy_find_dlls_log("Skip link item due to mode='${_next_item_mode}' item='${_item}' target='${target}'")
                continue()
            endif()

            _novaphy_extract_targets_from_link_item("${_item}" _dep_targets)
            foreach(_dep_target IN LISTS _dep_targets)
                _novaphy_resolve_alias_target("${_dep_target}" _dep_target)
                list(APPEND _targets "${_dep_target}")
            endforeach()
        endforeach()
    endforeach()

    # Also traverse explicit build-order dependencies added via add_dependencies().
    get_target_property(_manual_deps "${target}" MANUALLY_ADDED_DEPENDENCIES)
    if (_manual_deps AND NOT _manual_deps STREQUAL "_manual_deps-NOTFOUND")
        _novaphy_find_dlls_log("Target '${target}' MANUALLY_ADDED_DEPENDENCIES='${_manual_deps}'")
        foreach(_dep IN LISTS _manual_deps)
            if (TARGET "${_dep}")
                _novaphy_resolve_alias_target("${_dep}" _dep)
                list(APPEND _targets "${_dep}")
            endif()
        endforeach()
    endif()

    if (_targets)
        list(REMOVE_DUPLICATES _targets)
    endif()
    _novaphy_find_dlls_log("Resolved deps for '${target}': '${_targets}'")
    set(${out_targets} "${_targets}" PARENT_SCOPE)
endfunction()

function(_novaphy_target_is_runtime_library target out_is_runtime)
    set(_is_runtime FALSE)

    get_target_property(_dep_type "${target}" TYPE)
    if (_dep_type STREQUAL "SHARED_LIBRARY" OR _dep_type STREQUAL "MODULE_LIBRARY")
        set(_is_runtime TRUE)
    else()
        get_target_property(_is_imported "${target}" IMPORTED)
        if (_is_imported)
            get_target_property(_loc "${target}" IMPORTED_LOCATION)
            if (_loc)
                set(_is_runtime TRUE)
            else()
                foreach(_cfg IN ITEMS DEBUG RELEASE RELWITHDEBINFO MINSIZEREL)
                    get_target_property(_loc_cfg "${target}" "IMPORTED_LOCATION_${_cfg}")
                    if (_loc_cfg)
                        set(_is_runtime TRUE)
                        break()
                    endif()
                endforeach()

                if (NOT _is_runtime)
                    get_target_property(_implib "${target}" IMPORTED_IMPLIB)
                    if (_implib)
                        set(_is_runtime TRUE)
                    else()
                        foreach(_cfg IN ITEMS DEBUG RELEASE RELWITHDEBINFO MINSIZEREL)
                            get_target_property(_implib_cfg "${target}" "IMPORTED_IMPLIB_${_cfg}")
                            if (_implib_cfg)
                                set(_is_runtime TRUE)
                                break()
                            endif()
                        endforeach()
                    endif()
                endif()
            endif()
        endif()
    endif()

    get_target_property(_dep_type_dbg "${target}" TYPE)
    get_target_property(_is_imported_dbg "${target}" IMPORTED)
    _novaphy_find_dlls_log("Runtime check target='${target}' type='${_dep_type_dbg}' imported='${_is_imported_dbg}' -> ${_is_runtime}")

    set(${out_is_runtime} ${_is_runtime} PARENT_SCOPE)
endfunction()

function(_novaphy_append_imported_dll_from_implib implib out_refs)
    set(_refs "${${out_refs}}")
    if (WIN32 AND implib)
        get_filename_component(_implib_ext "${implib}" EXT)
        if (_implib_ext STREQUAL ".lib")
            get_filename_component(_implib_dir "${implib}" DIRECTORY)
            get_filename_component(_implib_name_we "${implib}" NAME_WE)
            set(_dll_guess "${_implib_dir}/${_implib_name_we}.dll")
            if (EXISTS "${_dll_guess}")
                list(APPEND _refs "${_dll_guess}")
            else()
                # Common vcpkg layout: installed/<triplet>/lib/*.lib -> installed/<triplet>/bin/*.dll
                string(REPLACE "/lib" "/bin" _dll_guess_bin "${_dll_guess}")
                string(REPLACE "\\lib" "\\bin" _dll_guess_bin "${_dll_guess_bin}")
                if (EXISTS "${_dll_guess_bin}")
                    list(APPEND _refs "${_dll_guess_bin}")
                endif()
            endif()
        endif()
    endif()
    set(${out_refs} "${_refs}" PARENT_SCOPE)
endfunction()

function(_novaphy_target_runtime_refs target out_refs)
    set(_refs "")

    get_target_property(_is_imported "${target}" IMPORTED)
    get_target_property(_dep_type "${target}" TYPE)

    if (_is_imported)
        # Prefer concrete imported locations for imported targets to avoid relying
        # on TARGET_FILE support of all imported target types.
        get_target_property(_loc "${target}" IMPORTED_LOCATION)
        if (_loc)
            list(APPEND _refs "${_loc}")
        endif()
        foreach(_cfg IN ITEMS DEBUG RELEASE RELWITHDEBINFO MINSIZEREL)
            get_target_property(_loc_cfg "${target}" "IMPORTED_LOCATION_${_cfg}")
            if (_loc_cfg)
                list(APPEND _refs "${_loc_cfg}")
            endif()
        endforeach()

        if (NOT _refs)
            get_target_property(_implib "${target}" IMPORTED_IMPLIB)
            if (_implib)
                _novaphy_find_dlls_log("Try implib fallback target='${target}' IMPORTED_IMPLIB='${_implib}'")
                _novaphy_append_imported_dll_from_implib("${_implib}" _refs)
            endif()
            foreach(_cfg IN ITEMS DEBUG RELEASE RELWITHDEBINFO MINSIZEREL)
                get_target_property(_implib_cfg "${target}" "IMPORTED_IMPLIB_${_cfg}")
                if (_implib_cfg)
                    _novaphy_find_dlls_log("Try implib fallback target='${target}' IMPORTED_IMPLIB_${_cfg}='${_implib_cfg}'")
                    _novaphy_append_imported_dll_from_implib("${_implib_cfg}" _refs)
                endif()
            endforeach()
        endif()
    endif()

    if (NOT _refs)
        if (_dep_type STREQUAL "SHARED_LIBRARY" OR _dep_type STREQUAL "MODULE_LIBRARY" OR _dep_type STREQUAL "EXECUTABLE")
            list(APPEND _refs "$<TARGET_FILE:${target}>")
        endif()
    endif()

    if (_refs)
        list(REMOVE_DUPLICATES _refs)
        _novaphy_find_dlls_log("Runtime refs for '${target}': '${_refs}'")
    else()
        _novaphy_find_dlls_log("No runtime ref resolved for target '${target}'")
    endif()
    set(${out_refs} "${_refs}" PARENT_SCOPE)
endfunction()

function(_novaphy_target_in_except target except_targets out_in_except)
    set(_in_except FALSE)

    _novaphy_resolve_alias_target("${target}" _target_resolved)
    foreach(_except IN LISTS except_targets)
        set(_except_resolved "${_except}")
        if (TARGET "${_except}")
            _novaphy_resolve_alias_target("${_except}" _except_resolved)
        endif()

        if ("${_target_resolved}" STREQUAL "${_except_resolved}" OR
            "${target}" STREQUAL "${_except}")
            set(_in_except TRUE)
            break()
        endif()
    endforeach()

    set(${out_in_except} ${_in_except} PARENT_SCOPE)
endfunction()

function(_find_target_dlls target out_dlls_var visited_var filter_imported except_targets)
    if (NOT TARGET "${target}")
        return()
    endif()

    _novaphy_resolve_alias_target("${target}" _target)
    _novaphy_find_dlls_log("Enter target='${target}' resolved='${_target}'")

    set(_visited "${${visited_var}}")
    list(FIND _visited "${_target}" _visited_idx)
    if (NOT _visited_idx EQUAL -1)
        _novaphy_find_dlls_log("Skip visited target='${_target}'")
        return()
    endif()
    list(APPEND _visited "${_target}")
    set(${visited_var} "${_visited}" PARENT_SCOPE)

    _novaphy_get_target_link_targets("${_target}" _deps)
    _novaphy_find_dlls_log("Inspect '${_target}', deps='${_deps}'")

    set(_dlls "${${out_dlls_var}}")
    foreach(_dep IN LISTS _deps)
        set(_skip_dep FALSE)
        if (filter_imported)
            get_target_property(_dep_imported "${_dep}" IMPORTED)
            if (_dep_imported)
                _novaphy_target_in_except("${_dep}" "${except_targets}" _dep_in_except)
                if (NOT _dep_in_except)
                    set(_skip_dep TRUE)
                    _novaphy_find_dlls_log("Skip imported dep target='${_dep}' (FILTER_IMPORTED enabled)")
                else()
                    _novaphy_find_dlls_log("Keep imported dep target='${_dep}' (matched EXCEPT)")
                endif()
            endif()
        endif()

        if (_skip_dep)
            continue()
        endif()

        _novaphy_target_is_runtime_library("${_dep}" _is_runtime)
        if (_is_runtime)
            _novaphy_target_runtime_refs("${_dep}" _dep_runtime_refs)
            if (_dep_runtime_refs)
                list(APPEND _dlls ${_dep_runtime_refs})
                _novaphy_find_dlls_log("Collect '${_dep}' -> '${_dep_runtime_refs}'")
            endif()
        endif()

        set(${out_dlls_var} "${_dlls}" PARENT_SCOPE)
        _find_target_dlls("${_dep}" ${out_dlls_var} ${visited_var} "${filter_imported}" "${except_targets}")
        set(_dlls "${${out_dlls_var}}")
        set(_visited "${${visited_var}}")
    endforeach()

    set(${out_dlls_var} "${_dlls}" PARENT_SCOPE)
    set(${visited_var} "${_visited}" PARENT_SCOPE)
endfunction()

function(find_target_dlls)
    set(_options FILTER_IMPORTED)
    set(_one_value_args TARGET OUT_VAR)
    set(_multi_value_args EXCEPT)
    cmake_parse_arguments(FTD "${_options}" "${_one_value_args}" "${_multi_value_args}" ${ARGN})

    set(_target "")
    if (FTD_TARGET)
        set(_target "${FTD_TARGET}")
    elseif (ARGC GREATER 0)
        set(_target "${ARGV0}")
    endif()

    if (NOT _target)
        message(FATAL_ERROR "find_target_dlls: missing target. Use find_target_dlls(TARGET <target> [OUT_VAR <var>])")
    endif()

    if (NOT TARGET "${_target}")
        message(FATAL_ERROR "find_target_dlls: target '${_target}' does not exist")
    endif()

    set(_out_var "")
    if (FTD_OUT_VAR)
        set(_out_var "${FTD_OUT_VAR}")
    elseif (NOT FTD_TARGET AND ARGC GREATER 1)
        set(_out_var "${ARGV1}")
    else()
        set(_out_var "${_target}_RUNTIME_DLLS")
    endif()

    set(_dlls "")
    set(_visited "")
    set(_filter_imported FALSE)
    if (FTD_FILTER_IMPORTED)
        set(_filter_imported TRUE)
    endif()

    set(_except_targets "${FTD_EXCEPT}")

    _novaphy_find_dlls_log("Options root='${_target}': FILTER_IMPORTED=${_filter_imported}, EXCEPT='${_except_targets}'")
    _find_target_dlls("${_target}" _dlls _visited "${_filter_imported}" "${_except_targets}")

    if (_dlls)
        list(REMOVE_DUPLICATES _dlls)
    endif()
    _novaphy_find_dlls_log("Final dll list for root='${_target}': '${_dlls}'")
    set(${_out_var} "${_dlls}" PARENT_SCOPE)
endfunction()
